title: Jacopo Orsini - Data Scientist
email: jacopo.orsini.ds@gmail.com
description: >- 
  I believe in showing up every day with intention, not just to get things done, but to grow through the process. Every challenge is an opportunity 
  to learn something new, to refine skills, and to stretch beyond It was thought possible. It is fundamental to approach each step with curiosity, resilience, 
  and positivity, knowing that consistency and a willingness to learn are what truly drive progress.
baseurl: ""
url: "https://jacopooorsinii.github.io"
linkedin_username: jacopo-orsini-366bb3173
github_username:  JacopooOrsinii

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation menu pages (these will appear in the top nav)
header_pages:
  - about.md
  - education.md
  - experiences.md
  - projects.md