title: Jacopo Orsini - Data Scientist
email: jacopo.orsini.ds@gmail.com
baseurl: ""
url: "https://jacopooorsinii.github.io"
linkedin_username: jacopo-orsini-366bb3173
github_username:  JacopooOrsinii

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation menu pages (these will appear in the top nav)
header_pages:
  - about.md
  - education.md
  - experiences.md
  - projects.md